export enum Role {
  SUDO_ADMIN = 'SUDO_ADMIN',
  ADMIN = 'ADMIN',
  COMPANY_SUPER_ADMIN = 'COMPANY_SUPER_ADMIN',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  COMPANY_EMPLOYEE = 'COMPANY_EMPLOYEE',
}

export enum Environment {
  PRODUCTION = 'PRODUCTION',
  DEVELOPMENT = 'DEVELOPMENT',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHERS = 'OTHERS',
}

export enum EmployeeStatus {
  TERMINATED = 'TERMINATED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
